### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pce16ec045** [ValentinGenard/Jarvis-artificial-intelligence#2]

**Comment by pce16ec045** [comment]
sir if we run jarvish file then show
>>>>>>>>>ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Say something!

error

**Comment by akshat9425** [comment]
@pce16ec045  I think its not error its telling you that speak some words that will be printed on command line
